### ISSUE TITLE
现在进行的怎么样了

### ISSUE THREAD

**Issue by haswelliris** [MarshallW906/DungeonMario_Cocos2dx#1]
我回来了，有什么需要老夫出手的吗

**Comment by MarshallW906** [comment]
要不要写个后端：记录高分榜
记每个关卡的过关用时（秒数），用的生命数

**Comment by haswelliris** [comment]
可以吧，我用node搭一个，接口文档写在wiki里，你在游戏里面发个post到服务器就行了

**Comment by MarshallW906** [comment]
你开个branch吧，写好了之后pull request告诉一下
